"""empty message

Revision ID: 0636ab412fd1
Revises: 
Create Date: 2024-02-05 17:06:59.793236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0636ab412fd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('azs_fuel_info',
    sa.Column('id', sa.Integer(), nullable=False, comment='id Заправочной станции'),
    sa.Column('price', sa.Numeric(scale=2), nullable=True, comment='Цена топлива'),
    sa.Column('type', sa.Enum('GASOLINE76', 'GASOLINE80', 'GASOLINE91', 'GASOLINE92', 'GASOLINE95', 'GASOLINE100', 'GASOLINE105', 'DIESEL', 'DIESEL_WINTER', 'AD_BLUE', name='fueltypes'), nullable=True, comment='Тип топлива'),
    sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', name='currencytypes'), nullable=True, comment='Тип валюты'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('azs_main_info',
    sa.Column('id', sa.Integer(), nullable=False, comment='id Заправочной станции'),
    sa.Column('tel_number', sa.String(length=20), nullable=True, comment='Номер телефона'),
    sa.Column('coords', sa.String(length=255), nullable=True, comment='Координаты АЗС'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='Адрес АЗС'),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=True, comment='Изображения'),
    sa.Column('services', sa.ARRAY(sa.String()), nullable=True, comment='Дополнительные Услуги'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('azs_main_info')
    op.drop_table('azs_fuel_info')
    # ### end Alembic commands ###
